# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
import plotly.figure_factory as ff

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [2]:
# Carregando bases de teste
X_test = pd.read_csv('Xp_test.csv')
y_test = pd.read_csv('Yp_test.csv')
X_train = pd.read_csv('xp_train_bal.csv')
y_train = pd.read_csv('yp_train_bal.csv')

In [4]:
X_test.describe()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,36.804878,0.365854,81158.536585,2.170732,0.365854,0.756098,0.317073
std,7.061230,0.487652,33690.213532,1.339822,0.487652,0.859665,0.471117
min,25.000000,0.000000,25000.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,0.000000,55000.000000,1.000000,0.000000,0.000000,0.000000
50%,36.000000,0.000000,85000.000000,2.000000,0.000000,1.000000,0.000000
75%,39.000000,1.000000,95000.000000,3.000000,1.000000,1.000000,1.000000
max,52.000000,1.000000,162500.000000,4.000000,1.000000,3.000000,1.000000

In [5]:
y_test.describe()

       Credit Score
count     41.000000
mean       1.000000
std        0.547723
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        2.000000

In [6]:
X_train.describe()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership
count,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000
mean,33.190476,0.317460,62517.045225,1.587302,0.742063,0.309524,0.654762
std,7.010197,0.466415,32400.375014,1.346501,0.438370,0.696769,0.476392
min,25.000000,0.000000,27500.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,0.000000,35520.696410,0.000000,0.000000,0.000000,0.000000
50%,31.000000,0.000000,53750.000000,1.000000,1.000000,0.000000,1.000000
75%,36.000000,1.000000,80000.000000,3.000000,1.000000,0.000000,1.000000
max,53.000000,1.000000,155000.000000,4.000000,1.000000,3.000000,1.000000

In [7]:
y_train.describe()

       Credit Score
count    252.000000
mean       1.000000
std        0.818121
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        2.000000

Bases carregadas e verificadas.

As divisões de coluna estão corretas e os dados de treino parecem balanceados

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [9]:
# Como o scikit pede um array unidimensional vou gerar uma variável para isso
y1_train = y_train.values.ravel()
# Aplicando bayes aos dados de treinamento
naive_cred = GaussianNB()
naive_cred.fit(X_train, y1_train)

GaussianNB()

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [10]:
# Acurácia do modelo de treino
y_pred_train = naive_cred.predict(X_train)
acc = accuracy_score(y1_train, y_pred_train)
print(f'Acurácia: {acc}')

Acurácia: 0.9801587301587301

In [11]:
# Fazendo o recall multi classe
recall = recall_score(y1_train, y_pred_train, average='macro')
print(f'Recall: {recall}')

Recall: 0.9801587301587302

In [15]:
conf_matrix = confusion_matrix(y1_train, y_pred_train)
# Lista de classes de crédito
cred_class = ['Baixo', 'Médio', 'Alto']
# Plotando a matriz de confusão
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=cred_class,
    y=cred_class,
    colorscale='PuBuGn',
    showscale=True,
)
fig.update_layout(
    template = 'simple_white',
    title = 'Matriz de confusão',
    xaxis_title= 'Predicted labels',
    yaxis_title= 'True labels',

)

O modelo se saiu muito bem na previsão dos dados do treino.

Obteve uma acurácia de 98% e um recall de mesma intensidade. Isso pode se dar pelo fato das variáveis relacionadas com a classificação de crédito terem uma relação mais independente entre si no nosso dataframe.

Obs: Não sei se tem relação também, mas quando eu fiz da maneira ensinada na aula recebi um aviso do python relacionado à maneira como os dados de 'y' estavam sendo dispostos para o modelo. Então eu corrigi de acordo com o recomendado no próprio aviso. Acho que isso deve ter ajudado o modelo de alguma maneira, mas posso estar enganado.

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [16]:
# Como o scikit pede um array unidimensional vou gerar uma variável para isso
y1_test = y_test.values.ravel()
# Aplicando bayes aos dados de treinamento
naive_tcred = GaussianNB()
naive_tcred.fit(X_test, y1_test)

GaussianNB()

In [17]:
# Acurácia do modelo de teste
y_pred_test = naive_cred.predict(X_test)
acct = accuracy_score(y1_test, y_pred_test)
print(f'Acurácia: {acct}')

Acurácia: 0.975609756097561

In [18]:
# Fazendo o recall multi classe
recall = recall_score(y1_test, y_pred_test, average='macro')
print(f'Recall: {recall}')

Recall: 0.9444444444444445

In [19]:
conf_matrix = confusion_matrix(y1_test, y_pred_test)
# Lista de classes de crédito
cred_class = ['Baixo', 'Médio', 'Alto']
# Plotando a matriz de confusão
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=cred_class,
    y=cred_class,
    colorscale='PuBuGn',
    showscale=True,
)
fig.update_layout(
    template = 'simple_white',
    title = 'Matriz de confusão',
    xaxis_title= 'Predicted labels',
    yaxis_title= 'True labels',

)

O modelo de teste teve uma acurácia muito próxima do modelo de treino (cerca de 1%), o que pode significar que o modelo de Naive Bayes se encaixou bem no nosso dataframe.

Um ponto interessante é o desempenho do recall ser menor, mas considerando o volume de dados do teste eu diria que 1 erro é bastante impressionante.

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Utilize pelo menos 4 linhas.

Dica: Caso você ainda esteja tendo dificuldade em visualizar a aplicação dos projetos e objetivo, consulte seus tutores!

O projeto desenvolvido nessa atividade (em conjunto com o módulo 17) foi a análise, limpeza, preparação e montagem de um modelo de machine learning baseado em Naive Bayes para uma companhia de crédito.

O projeto de machine learning tinha como objetivo automatizar e tentar predizer o score de crédito correto a ser cedido para um cliente baseado em seus dados coletados. O score variava entre baixo, médio e alto.

O Naive Bayes foi aplicado à base de crédito por ter uma boa performance de predição quando lida com variáveis independentes entre sí. Como a base de dados que alimentava o modelo para a predição era composta por dados independentes, o modelo conseguiu entregar boa performance.